/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vectori
 */
public class Luces extends javax.swing.JFrame {
    int encendidas = 0;
    int apagadas = 0;
    
    ImageIcon apagado = new ImageIcon(getClass().getResource("/imagen/focoApagado.jpg"));
    ImageIcon encendido= new ImageIcon(getClass().getResource("/imagen/focoEncendido.jpg"));
    Icon off;
    Icon on;
    
    /**
     * Creates new form Luces
     */
    public Luces() {
        initComponents();
        this.setLocationRelativeTo(null);// sirve para centrar el JFrame
        
        off = new ImageIcon(apagado.getImage().getScaledInstance(lblLP1.getWidth(),lblLP1.getHeight(), Image.SCALE_DEFAULT));
        on = new ImageIcon(encendido.getImage().getScaledInstance(lblLP1.getWidth(),lblLP1.getHeight(), Image.SCALE_DEFAULT));
        
        JLabel [] labels = {lblLP1, lblLP2, lblLP3, lblLS1, lblLS2, lblLS3, lblLdS1, lblLdS2, lblLdS3};
        for(JLabel label : labels){
            label.setIcon(off);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnSecundario = new javax.swing.JPopupMenu();
        mnpapagarTodas = new javax.swing.JMenuItem();
        mnEncenderTodas = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnSdia = new javax.swing.JMenuItem();
        mnSnoche = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnSprincipales = new javax.swing.JMenuItem();
        mnSsecundarios = new javax.swing.JMenuItem();
        mnSseguridad = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        chkOf1LP = new javax.swing.JCheckBox();
        chkOf1LS = new javax.swing.JCheckBox();
        chkOf1LdS = new javax.swing.JCheckBox();
        lblLP1 = new javax.swing.JLabel();
        lblLS1 = new javax.swing.JLabel();
        lblLdS1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkOf2LP = new javax.swing.JCheckBox();
        chkOf2LS = new javax.swing.JCheckBox();
        chkOf2LdS = new javax.swing.JCheckBox();
        lblLP2 = new javax.swing.JLabel();
        lblLdS2 = new javax.swing.JLabel();
        lblLS2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chkOf3LP = new javax.swing.JCheckBox();
        chkOf3LS = new javax.swing.JCheckBox();
        chkOf3LdS = new javax.swing.JCheckBox();
        lblLS3 = new javax.swing.JLabel();
        lblLdS3 = new javax.swing.JLabel();
        lblLP3 = new javax.swing.JLabel();
        mnBarra = new javax.swing.JMenuBar();
        mnActivacion = new javax.swing.JMenu();
        mnApagarT = new javax.swing.JMenuItem();
        mnEncenderT = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnDia = new javax.swing.JMenu();
        mnDiaOf1 = new javax.swing.JMenuItem();
        mnDiaOf2 = new javax.swing.JMenuItem();
        mnDiaOf3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnDiaTodas = new javax.swing.JMenuItem();
        mnNoche = new javax.swing.JMenu();
        mnNocheOf1 = new javax.swing.JMenuItem();
        mnNocheOf2 = new javax.swing.JMenuItem();
        mnNocheOf3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnNocheT = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        mnPrincipal = new javax.swing.JMenu();
        mnPrincipales = new javax.swing.JMenuItem();
        mnSecundarias = new javax.swing.JMenuItem();
        mnSeguridad = new javax.swing.JMenuItem();
        mnAcercaDe = new javax.swing.JMenuItem();

        mnpapagarTodas.setText("Apagar Todas");
        mnpapagarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpapagarTodasActionPerformed(evt);
            }
        });
        mnSecundario.add(mnpapagarTodas);

        mnEncenderTodas.setText("Encender Todas");
        mnEncenderTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEncenderTodasActionPerformed(evt);
            }
        });
        mnSecundario.add(mnEncenderTodas);
        mnSecundario.add(jSeparator5);

        mnSdia.setText("Dia");
        mnSdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSdiaActionPerformed(evt);
            }
        });
        mnSecundario.add(mnSdia);

        mnSnoche.setText("Noche");
        mnSnoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSnocheActionPerformed(evt);
            }
        });
        mnSecundario.add(mnSnoche);
        mnSecundario.add(jSeparator6);

        mnSprincipales.setText("Principales");
        mnSprincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSprincipalesActionPerformed(evt);
            }
        });
        mnSecundario.add(mnSprincipales);

        mnSsecundarios.setText("Secundario");
        mnSsecundarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSsecundariosActionPerformed(evt);
            }
        });
        mnSecundario.add(mnSsecundarios);

        mnSseguridad.setText("Seguridad");
        mnSseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSseguridadActionPerformed(evt);
            }
        });
        mnSecundario.add(mnSseguridad);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Luces de Oficinas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setComponentPopupMenu(mnSecundario);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Oficina 1"));

        chkOf1LP.setText("Luz Principal");
        chkOf1LP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf1LPStateChanged(evt);
            }
        });

        chkOf1LS.setText("Luz Secundaria");
        chkOf1LS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf1LSStateChanged(evt);
            }
        });

        chkOf1LdS.setText("Luz de Seguridad");
        chkOf1LdS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf1LdSStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkOf1LP)
                    .addComponent(chkOf1LS)
                    .addComponent(chkOf1LdS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLS1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLdS1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOf1LP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOf1LS)
                    .addComponent(lblLS1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOf1LdS)
                    .addComponent(lblLdS1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Oficina 2"));

        chkOf2LP.setText("Luz Principal");
        chkOf2LP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf2LPStateChanged(evt);
            }
        });

        chkOf2LS.setText("Luz Secundaria");
        chkOf2LS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf2LSStateChanged(evt);
            }
        });

        chkOf2LdS.setText("Luz de Seguridad");
        chkOf2LdS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf2LdSStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkOf2LP)
                    .addComponent(chkOf2LS)
                    .addComponent(chkOf2LdS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblLS2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLdS2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkOf2LP)
                    .addComponent(lblLP2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLS2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOf2LS))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLdS2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOf2LdS))
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(" Oficina 3"));

        chkOf3LP.setText("Luz Principal");
        chkOf3LP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf3LPStateChanged(evt);
            }
        });

        chkOf3LS.setText("Luz Secundaria");
        chkOf3LS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf3LSStateChanged(evt);
            }
        });

        chkOf3LdS.setText("Luz de Seguridad");
        chkOf3LdS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOf3LdSStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkOf3LP)
                    .addComponent(chkOf3LS)
                    .addComponent(chkOf3LdS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLP3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLdS3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLS3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(chkOf3LP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLP3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLS3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOf3LS))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLdS3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOf3LdS))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        mnActivacion.setText("Activación");
        mnActivacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnActivacionActionPerformed(evt);
            }
        });

        mnApagarT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnApagarT.setText("Apagar Todas");
        mnApagarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnApagarTActionPerformed(evt);
            }
        });
        mnActivacion.add(mnApagarT);

        mnEncenderT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnEncenderT.setText("Encender Todas");
        mnEncenderT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEncenderTActionPerformed(evt);
            }
        });
        mnActivacion.add(mnEncenderT);
        mnActivacion.add(jSeparator1);

        mnDia.setText("Día");

        mnDiaOf1.setText("Oficina 1");
        mnDiaOf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiaOf1ActionPerformed(evt);
            }
        });
        mnDia.add(mnDiaOf1);

        mnDiaOf2.setText("Oficina 2");
        mnDiaOf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiaOf2ActionPerformed(evt);
            }
        });
        mnDia.add(mnDiaOf2);

        mnDiaOf3.setText("Oficina 3");
        mnDiaOf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiaOf3ActionPerformed(evt);
            }
        });
        mnDia.add(mnDiaOf3);
        mnDia.add(jSeparator3);

        mnDiaTodas.setText("Todas");
        mnDiaTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiaTodasActionPerformed(evt);
            }
        });
        mnDia.add(mnDiaTodas);

        mnActivacion.add(mnDia);

        mnNoche.setText("Noche");
        mnNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNocheActionPerformed(evt);
            }
        });

        mnNocheOf1.setText("Oficina 1");
        mnNocheOf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNocheOf1ActionPerformed(evt);
            }
        });
        mnNoche.add(mnNocheOf1);

        mnNocheOf2.setText("Oficina 2");
        mnNocheOf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNocheOf2ActionPerformed(evt);
            }
        });
        mnNoche.add(mnNocheOf2);

        mnNocheOf3.setText("Oficina 3");
        mnNocheOf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNocheOf3ActionPerformed(evt);
            }
        });
        mnNoche.add(mnNocheOf3);
        mnNoche.add(jSeparator4);

        mnNocheT.setText("Todas");
        mnNocheT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNocheTActionPerformed(evt);
            }
        });
        mnNoche.add(mnNocheT);

        mnActivacion.add(mnNoche);
        mnActivacion.add(jSeparator2);

        mnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnActivacion.add(mnSalir);

        mnBarra.add(mnActivacion);

        mnPrincipal.setText("Info");

        mnPrincipales.setText("Principales");
        mnPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrincipalesActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnPrincipales);

        mnSecundarias.setText("Secundarias");
        mnSecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSecundariasActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnSecundarias);

        mnSeguridad.setText("Seguridad");
        mnSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSeguridadActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnSeguridad);

        mnAcercaDe.setText("Acerca de...");
        mnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAcercaDeActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnAcercaDe);

        mnBarra.add(mnPrincipal);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnActivacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnActivacionActionPerformed
        
    }//GEN-LAST:event_mnActivacionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void mnEncenderTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEncenderTActionPerformed
        chkOf1LP.setSelected(true);
        chkOf1LS.setSelected(true);
        chkOf1LdS.setSelected(true);
        chkOf2LP.setSelected(true);
        chkOf2LS.setSelected(true);
        chkOf2LdS.setSelected(true);
        chkOf3LP.setSelected(true);
        chkOf3LS.setSelected(true);
        chkOf3LdS.setSelected(true);
    }//GEN-LAST:event_mnEncenderTActionPerformed

    private void mnApagarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnApagarTActionPerformed
        chkOf1LP.setSelected(false);
        chkOf1LS.setSelected(false);
        chkOf1LdS.setSelected(false);
        chkOf2LP.setSelected(false);
        chkOf2LS.setSelected(false);
        chkOf2LdS.setSelected(false);
        chkOf3LP.setSelected(false);
        chkOf3LS.setSelected(false);
        chkOf3LdS.setSelected(false);
    }//GEN-LAST:event_mnApagarTActionPerformed

    private void mnDiaOf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiaOf1ActionPerformed
        chkOf1LP.setSelected(true);
        chkOf1LS.setSelected(true);
        chkOf1LdS.setSelected(false);
    }//GEN-LAST:event_mnDiaOf1ActionPerformed

    private void mnDiaOf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiaOf2ActionPerformed
        chkOf2LP.setSelected(true);
        chkOf2LS.setSelected(true);
        chkOf2LdS.setSelected(false);
    }//GEN-LAST:event_mnDiaOf2ActionPerformed

    private void mnDiaOf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiaOf3ActionPerformed
        chkOf3LP.setSelected(true);
        chkOf3LS.setSelected(true);
        chkOf3LdS.setSelected(false);
    }//GEN-LAST:event_mnDiaOf3ActionPerformed

    private void mnDiaTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiaTodasActionPerformed
        chkOf1LP.setSelected(true);
        chkOf1LS.setSelected(true);
        chkOf1LdS.setSelected(false);
        chkOf2LP.setSelected(true);
        chkOf2LS.setSelected(true);
        chkOf2LdS.setSelected(false);
        chkOf3LP.setSelected(true);
        chkOf3LS.setSelected(true);
        chkOf3LdS.setSelected(false);
    }//GEN-LAST:event_mnDiaTodasActionPerformed

    private void mnNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnNocheActionPerformed

    private void mnNocheOf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNocheOf1ActionPerformed
        chkOf1LP.setSelected(false);
        chkOf1LS.setSelected(false);
        chkOf1LdS.setSelected(true);
    }//GEN-LAST:event_mnNocheOf1ActionPerformed

    private void mnNocheOf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNocheOf2ActionPerformed
        chkOf2LP.setSelected(false);
        chkOf2LS.setSelected(false);
        chkOf2LdS.setSelected(true);
    }//GEN-LAST:event_mnNocheOf2ActionPerformed

    private void mnNocheOf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNocheOf3ActionPerformed
        chkOf3LP.setSelected(false);
        chkOf3LS.setSelected(false);
        chkOf3LdS.setSelected(true);
    }//GEN-LAST:event_mnNocheOf3ActionPerformed

    private void mnNocheTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNocheTActionPerformed
        chkOf1LP.setSelected(false);
        chkOf1LS.setSelected(false);
        chkOf1LdS.setSelected(true);
        chkOf2LP.setSelected(false);
        chkOf2LS.setSelected(false);
        chkOf2LdS.setSelected(true);
        chkOf3LP.setSelected(false);
        chkOf3LS.setSelected(false);
        chkOf3LdS.setSelected(true);
    }//GEN-LAST:event_mnNocheTActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        int mnSalir = JOptionPane.showConfirmDialog(null, "Desae salir", "Mensaje de Confirmacion", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(mnSalir==0){
            System.exit(0);
        }else{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrincipalesActionPerformed
        JCheckBox[] checks = {chkOf1LP,chkOf2LP,chkOf3LP};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces Principales" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = apagadas = 0;
    }//GEN-LAST:event_mnPrincipalesActionPerformed

    private void mnSecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSecundariasActionPerformed
        JCheckBox[] checks = {chkOf1LS,chkOf2LS,chkOf3LS};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces Secundarias" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = apagadas = 0;
    }//GEN-LAST:event_mnSecundariasActionPerformed

    private void mnSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSeguridadActionPerformed
        JCheckBox[] checks = {chkOf1LdS,chkOf2LdS,chkOf3LdS};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces de Seguridad" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = 0;
        apagadas = 0;
    }//GEN-LAST:event_mnSeguridadActionPerformed

    private void mnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAcercaDeActionPerformed
        JOptionPane.showMessageDialog(null, "111 mil programadores" + "\nVettori Alberto Andres ");
    }//GEN-LAST:event_mnAcercaDeActionPerformed

    private void chkOf1LPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf1LPStateChanged
        if(chkOf1LP.isSelected()) lblLP1.setIcon(on);
        else lblLP1.setIcon(off);
    }//GEN-LAST:event_chkOf1LPStateChanged

    private void mnpapagarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpapagarTodasActionPerformed
        chkOf1LP.setSelected(false);
        chkOf1LS.setSelected(false);
        chkOf1LdS.setSelected(false);
        chkOf2LP.setSelected(false);
        chkOf2LS.setSelected(false);
        chkOf2LdS.setSelected(false);
        chkOf3LP.setSelected(false);
        chkOf3LS.setSelected(false);
        chkOf3LdS.setSelected(false);
    }//GEN-LAST:event_mnpapagarTodasActionPerformed

    private void mnEncenderTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEncenderTodasActionPerformed
        chkOf1LP.setSelected(true);
        chkOf1LS.setSelected(true);
        chkOf1LdS.setSelected(true);
        chkOf2LP.setSelected(true);
        chkOf2LS.setSelected(true);
        chkOf2LdS.setSelected(true);
        chkOf3LP.setSelected(true);
        chkOf3LS.setSelected(true);
        chkOf3LdS.setSelected(true);
    }//GEN-LAST:event_mnEncenderTodasActionPerformed

    private void chkOf1LSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf1LSStateChanged
        if(chkOf1LS.isSelected()) lblLS1.setIcon(on);
        else lblLS1.setIcon(off);
    }//GEN-LAST:event_chkOf1LSStateChanged

    private void chkOf1LdSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf1LdSStateChanged
        if(chkOf1LdS.isSelected()) lblLdS1.setIcon(on);
        else lblLdS1.setIcon(off);
    }//GEN-LAST:event_chkOf1LdSStateChanged

    private void chkOf2LPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf2LPStateChanged
        if(chkOf2LP.isSelected()) lblLP2.setIcon(on);
        else lblLP2.setIcon(off);
    }//GEN-LAST:event_chkOf2LPStateChanged

    private void chkOf2LSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf2LSStateChanged
        if(chkOf2LS.isSelected()) lblLS2.setIcon(on);
        else lblLS2.setIcon(off);
    }//GEN-LAST:event_chkOf2LSStateChanged

    private void chkOf2LdSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf2LdSStateChanged
        if(chkOf2LdS.isSelected()) lblLdS2.setIcon(on);
        else lblLdS2.setIcon(off);
    }//GEN-LAST:event_chkOf2LdSStateChanged

    private void chkOf3LPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf3LPStateChanged
        if(chkOf3LP.isSelected()) lblLP3.setIcon(on);
        else lblLP3.setIcon(off);
    }//GEN-LAST:event_chkOf3LPStateChanged

    private void chkOf3LSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf3LSStateChanged
        if(chkOf3LS.isSelected()) lblLS3.setIcon(on);
        else lblLS3.setIcon(off);
    }//GEN-LAST:event_chkOf3LSStateChanged

    private void chkOf3LdSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOf3LdSStateChanged
        if(chkOf3LdS.isSelected()) lblLdS3.setIcon(on);
        else lblLdS3.setIcon(off);
    }//GEN-LAST:event_chkOf3LdSStateChanged

    private void mnSdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSdiaActionPerformed
        chkOf1LP.setSelected(true);
        chkOf1LS.setSelected(true);
        chkOf1LdS.setSelected(false);
        chkOf2LP.setSelected(true);
        chkOf2LS.setSelected(true);
        chkOf2LdS.setSelected(false);
        chkOf3LP.setSelected(true);
        chkOf3LS.setSelected(true);
        chkOf3LdS.setSelected(false);
    }//GEN-LAST:event_mnSdiaActionPerformed

    private void mnSnocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSnocheActionPerformed
        chkOf1LP.setSelected(false);
        chkOf1LS.setSelected(false);
        chkOf1LdS.setSelected(true);
        chkOf2LP.setSelected(false);
        chkOf2LS.setSelected(false);
        chkOf2LdS.setSelected(true);
        chkOf3LP.setSelected(false);
        chkOf3LS.setSelected(false);
        chkOf3LdS.setSelected(true);
    }//GEN-LAST:event_mnSnocheActionPerformed

    private void mnSprincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSprincipalesActionPerformed
        JCheckBox[] checks = {chkOf1LP,chkOf2LP,chkOf3LP};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces Principales" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = apagadas = 0;
    }//GEN-LAST:event_mnSprincipalesActionPerformed

    private void mnSsecundariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSsecundariosActionPerformed
        JCheckBox[] checks = {chkOf1LS,chkOf2LS,chkOf3LS};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces Secundarias" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = apagadas = 0;
    }//GEN-LAST:event_mnSsecundariosActionPerformed

    private void mnSseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSseguridadActionPerformed
        JCheckBox[] checks = {chkOf1LdS,chkOf2LdS,chkOf3LdS};
        for (JCheckBox check : checks){
            if (check.isSelected()==true){
                encendidas ++;
                
            }else{
                apagadas++;
            }
        }
        JOptionPane.showMessageDialog(null, "Luces de Seguridad" + "\nEncendidas: " + encendidas + "\nApagadas: " + apagadas);
        encendidas = 0;
        apagadas = 0;
    }//GEN-LAST:event_mnSseguridadActionPerformed
    public void cerrar(){ 
        
    int eleccion = JOptionPane.showConfirmDialog(null, "Desae salir", "Mensaje de Cofirmacion", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if(eleccion == 0){
            System.exit(0);
        }else{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
            Thread.sleep(4000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Luces.class.getName()).log(Level.SEVERE, null, ex);
        }
                new Luces().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkOf1LP;
    private javax.swing.JCheckBox chkOf1LS;
    private javax.swing.JCheckBox chkOf1LdS;
    private javax.swing.JCheckBox chkOf2LP;
    private javax.swing.JCheckBox chkOf2LS;
    private javax.swing.JCheckBox chkOf2LdS;
    private javax.swing.JCheckBox chkOf3LP;
    private javax.swing.JCheckBox chkOf3LS;
    private javax.swing.JCheckBox chkOf3LdS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblLP1;
    private javax.swing.JLabel lblLP2;
    private javax.swing.JLabel lblLP3;
    private javax.swing.JLabel lblLS1;
    private javax.swing.JLabel lblLS2;
    private javax.swing.JLabel lblLS3;
    private javax.swing.JLabel lblLdS1;
    private javax.swing.JLabel lblLdS2;
    private javax.swing.JLabel lblLdS3;
    private javax.swing.JMenuItem mnAcercaDe;
    private javax.swing.JMenu mnActivacion;
    private javax.swing.JMenuItem mnApagarT;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnDia;
    private javax.swing.JMenuItem mnDiaOf1;
    private javax.swing.JMenuItem mnDiaOf2;
    private javax.swing.JMenuItem mnDiaOf3;
    private javax.swing.JMenuItem mnDiaTodas;
    private javax.swing.JMenuItem mnEncenderT;
    private javax.swing.JMenuItem mnEncenderTodas;
    private javax.swing.JMenu mnNoche;
    private javax.swing.JMenuItem mnNocheOf1;
    private javax.swing.JMenuItem mnNocheOf2;
    private javax.swing.JMenuItem mnNocheOf3;
    private javax.swing.JMenuItem mnNocheT;
    private javax.swing.JMenu mnPrincipal;
    private javax.swing.JMenuItem mnPrincipales;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnSdia;
    private javax.swing.JMenuItem mnSecundarias;
    private javax.swing.JPopupMenu mnSecundario;
    private javax.swing.JMenuItem mnSeguridad;
    private javax.swing.JMenuItem mnSnoche;
    private javax.swing.JMenuItem mnSprincipales;
    private javax.swing.JMenuItem mnSsecundarios;
    private javax.swing.JMenuItem mnSseguridad;
    private javax.swing.JMenuItem mnpapagarTodas;
    // End of variables declaration//GEN-END:variables
}
